# Result checking for PANDAS and SPARK version

## Import necessary libraries

In [1]:
# Add current directory to Python path for imports
import os
import sys

# Add the parent directory (project root) to Python path so we can import from src
project_root = os.path.dirname(os.getcwd())
if project_root not in sys.path:
    sys.path.append(project_root)

In [2]:
import pandas as pd

---

## Load the datasets

In [3]:
RAW_PATH = os.path.join("..", "data", "raw", "bangkok_traffy.csv")
PANDAS_VER_PATH = os.path.join("..", "data", "processed", "cleansed_data.csv")
SPARK_VER_PATH = os.path.join("..", "data", "processed", "cleansed_data_spark.csv")

# Load the datasets
raw_df = pd.read_csv(RAW_PATH, engine="python")
pandas_df = pd.read_csv(PANDAS_VER_PATH, engine="python")
spark_df = pd.read_csv(SPARK_VER_PATH, engine="python")

columns = pandas_df.columns.tolist()
spark_df = spark_df.loc[:, columns]

raw_df.sort_values(by=raw_df.columns.tolist(), inplace=True)
pandas_df.sort_values(by=pandas_df.columns.tolist(), inplace=True)
spark_df.sort_values(by=spark_df.columns.tolist(), inplace=True)

raw_df.reset_index(drop=True, inplace=True)
pandas_df.reset_index(drop=True, inplace=True)
spark_df.reset_index(drop=True, inplace=True)

---

## Check for basic information

In [4]:
print("Raw DataFrame shape:", raw_df.shape)
print("Pandas DataFrame shape:", pandas_df.shape)
print("Spark DataFrame shape:", spark_df.shape)

print()

print(f"Check: {pandas_df.shape == spark_df.shape}")

Raw DataFrame shape: (787026, 16)
Pandas DataFrame shape: (697885, 17)
Spark DataFrame shape: (697885, 17)

Check: True

In [5]:
display(raw_df.head(3))
display(pandas_df.head(3))
display(spark_df.head(3))

,ticket_id,type,organization,comment,photo,photo_after,coords,address,subdistrict,district,province,timestamp,state,star,count_reopen,last_activity
0,2021-4D9Y98,{},"เขตลาดพร้าว,การไฟฟ้านครหลวง เขตนวลจันทร์",หน้าปากซอย ลาดพร้าววังหิน26,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.59131,13.80910",17/73 17/73 ถ. ลาดพร้าววังหิน แขวงลาดพร้าว เขต...,ลาดพร้าว,ลาดพร้าว,กรุงเทพมหานคร,2021-12-13 05:53:36.861064+00,เสร็จสิ้น,NaN,0,2023-03-14 12:09:14.947437+00
1,2021-7K6QA3,{},"เขตประเวศ,ฝ่ายเทศกิจ เขตประเวศ",ระยะหลังๆ นี้ พบเจอรถสิบล้อขนดิน ใส่ยางบังโคลน...,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.65617,13.72812",208/22 ถ. พัฒนาการ แขวง ประเวศ เขต ประเวศ กรุง...,ประเวศ,ประเวศ,กรุงเทพมหานคร,2021-12-21 23:03:58.450912+00,เสร็จสิ้น,2.0,0,2022-06-24 06:32:34.671236+00
2,2021-7U9RED,{},เขตดุสิต,ยังไม่มีหน่วยงานไหนมาดูแลครับ รถจะเชี่ยวหลายคน...,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.50848,13.77832",627 ถนนสามเสน แขวง ดุสิต เขตดุสิต กรุงเทพมหานค...,ดุสิต,ดุสิต,กรุงเทพมหานคร,2021-12-17 08:46:02.610983+00,เสร็จสิ้น,5.0,0,2023-05-17 06:11:32.463984+00

,ticket_id,type,organization,comment,address,subdistrict,district,province,status,timestamp_date,timestamp_month,timestamp_year,last_activity_date,last_activity_month,last_activity_year,longitude,latitude
0,2021-4D9Y98,{},"เขตลาดพร้าว,การไฟฟ้านครหลวง เขตนวลจันทร์",หน้าปากซอย ลาดพร้าววังหิน26,17/73 17/73 ถ. ลาดพร้าววังหิน แขวงลาดพร้าว เขต...,ลาดพร้าว,ลาดพร้าว,กรุงเทพมหานคร,done,13,12,2021,14,3,2023,100.59131,13.80910
1,2021-7K6QA3,{},"เขตประเวศ,ฝ่ายเทศกิจ เขตประเวศ",ระยะหลังๆ นี้ พบเจอรถสิบล้อขนดิน ใส่ยางบังโคลน...,208/22 ถ. พัฒนาการ แขวง ประเวศ เขต ประเวศ กรุง...,ประเวศ,ประเวศ,กรุงเทพมหานคร,done,21,12,2021,24,6,2022,100.65617,13.72812
2,2021-7U9RED,{},เขตดุสิต,ยังไม่มีหน่วยงานไหนมาดูแลครับ รถจะเชี่ยวหลายคน...,627 ถนนสามเสน แขวง ดุสิต เขตดุสิต กรุงเทพมหานค...,ดุสิต,ดุสิต,กรุงเทพมหานคร,done,17,12,2021,17,5,2023,100.50848,13.77832

,ticket_id,type,organization,comment,address,subdistrict,district,province,status,timestamp_date,timestamp_month,timestamp_year,last_activity_date,last_activity_month,last_activity_year,longitude,latitude
0,2021-4D9Y98,{},"เขตลาดพร้าว,การไฟฟ้านครหลวง เขตนวลจันทร์",หน้าปากซอย ลาดพร้าววังหิน26,17/73 17/73 ถ. ลาดพร้าววังหิน แขวงลาดพร้าว เขต...,ลาดพร้าว,ลาดพร้าว,กรุงเทพมหานคร,done,13,12,2021,14,3,2023,100.59131,13.80910
1,2021-7K6QA3,{},"เขตประเวศ,ฝ่ายเทศกิจ เขตประเวศ",ระยะหลังๆ นี้ พบเจอรถสิบล้อขนดิน ใส่ยางบังโคลน...,208/22 ถ. พัฒนาการ แขวง ประเวศ เขต ประเวศ กรุง...,ประเวศ,ประเวศ,กรุงเทพมหานคร,done,22,12,2021,24,6,2022,100.65617,13.72812
2,2021-7U9RED,{},เขตดุสิต,ยังไม่มีหน่วยงานไหนมาดูแลครับ รถจะเชี่ยวหลายคน...,627 ถนนสามเสน แขวง ดุสิต เขตดุสิต กรุงเทพมหานค...,ดุสิต,ดุสิต,กรุงเทพมหานคร,done,17,12,2021,17,5,2023,100.50848,13.77832

---

## Check for PANDAS version reliability

In [6]:
df_raw_not_pandas = raw_df[~raw_df["ticket_id"].isin(pandas_df["ticket_id"])]

print("Rows in RAW but not in PANDAS:", df_raw_not_pandas.shape[0])

Rows in RAW but not in PANDAS: 89141

In [7]:
df_raw_not_pandas.head(3)

,ticket_id,type,organization,comment,photo,photo_after,coords,address,subdistrict,district,province,timestamp,state,star,count_reopen,last_activity
6,2021-9U2NJT,{น้ำท่วม},"เขตบางซื่อ,ฝ่ายโยธา เขตบางซื่อ",น้ำท่วม,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.53099,13.81853",12/14 ถนน กรุงเทพ- นนทบุรี แขวง บางซื่อ เขตบาง...,NaN,NaN,กรุงเทพมหานคร,2021-10-14 10:45:27.713884+00,เสร็จสิ้น,NaN,0,2022-09-08 08:35:43.784519+00
11,2021-FYJTFP,{ความสะอาด},เขตบางซื่อ,ขยะเยอะ,https://storage.googleapis.com/traffy_public_b...,NaN,"100.53084,13.81865",12/14 ถนน กรุงเทพ- นนทบุรี แขวง บางซื่อ เขตบาง...,NaN,NaN,กรุงเทพมหานคร,2021-09-03 12:51:09.453003+00,เสร็จสิ้น,NaN,0,2022-06-04 15:34:14.609206+00
29,2022-32444C,{ต้นไม้},"เขตบางบอน,ฝ่ายรักษาความสะอาดฯ เขตบางบอน,ผอ.เขต...",ปากซอยเอกชัย133 มีการปลูกต้นไม้ใหญ่และปลูกไม้พ...,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.37112,13.63782",4/11 ถ. เอกชัย แขวง บางบอน เขตบางบอน กรุงเทพมห...,บางบอนเหนือ,บางบอน,กรุงเทพมหานคร,2022-06-30 02:15:16.835639+00,เสร็จสิ้น,5.0,0,2022-06-30 08:24:10.868508+00

In [8]:
import geopandas as gpd

from src.pipelines import DistrictSubdistrictTransformer
from src.utils import load_geographic_data

dst = DistrictSubdistrictTransformer(
    district_column="DISTRICT_N",
    subdistrict_column="SUBDISTR_1",
    prefix_bonus=True,
)

raw_geo_df = load_geographic_data()
result_df = pd.DataFrame(dst.fit_transform(raw_geo_df))

bangkok_gdf = gpd.GeoDataFrame(result_df, crs="EPSG:4326")

bangkok_gdf.groupby(["DISTRICT_N", "SUBDISTR_1"]).size().reset_index(
    name="counts"
).sort_values(by="counts", ascending=False)

duplicates = bangkok_gdf[
    bangkok_gdf.duplicated(subset=["DISTRICT_N", "SUBDISTR_1"], keep=False)
]
duplicates = duplicates.sort_values(by=["DISTRICT_N", "SUBDISTR_1"])

if duplicates.empty:
    print("No duplicates found.")
else:
    display(duplicates[["DISTRICT_N", "SUBDISTR_1"]])

No duplicates found.

In [9]:
df_raw_not_pandas_bangkok = df_raw_not_pandas[
    (
        (df_raw_not_pandas["province"] == "กรุงเทพมหานคร")
        & (~df_raw_not_pandas["district"].isnull())
        & (~df_raw_not_pandas["subdistrict"].isnull())
    )
]

df_raw_not_pandas_bangkok.shape

(77216, 16)

---

## Get different

In [10]:
# Cast ticket_id to string for accurate comparison
pandas_df["ticket_id"] = pandas_df["ticket_id"].astype("str")
spark_df["ticket_id"] = spark_df["ticket_id"].astype("str")


# Get Columns
columns = pandas_df.columns.tolist()
columns_indicated = [col + "_x" if col != "ticket_id" else col for col in columns]

columns_mapping = dict(zip(columns_indicated, columns))


# Join and get differences
df_pandas_not_spark = (
    pandas_df.merge(
        spark_df, on="ticket_id", how="left", indicator=True, suffixes=("_x", "_y")
    )
    .query('_merge == "left_only"')
    .drop(columns=["_merge"])
)

df_spark_not_pandas = (
    spark_df.merge(
        pandas_df, on="ticket_id", how="left", indicator=True, suffixes=("_x", "_y")
    )
    .query('_merge == "left_only"')
    .drop(columns=["_merge"])
)


# Rename columns for clarity
df_pandas_not_spark = df_pandas_not_spark.loc[:, columns_indicated]
df_pandas_not_spark = df_pandas_not_spark.rename(columns=columns_mapping)

df_spark_not_pandas = df_spark_not_pandas.loc[:, columns_indicated]
df_spark_not_pandas = df_spark_not_pandas.rename(columns=columns_mapping)


# Output the number of different rows
print("Rows in Pandas but not in Spark:", df_pandas_not_spark.shape[0])
print("Rows in Spark but not in Pandas:", df_spark_not_pandas.shape[0])

Rows in Pandas but not in Spark: 45
Rows in Spark but not in Pandas: 45

In [11]:
if df_pandas_not_spark.shape[0] > 0:
    display(df_pandas_not_spark.head(3))

if df_spark_not_pandas.shape[0] > 0:
    display(df_spark_not_pandas.head(3))

,ticket_id,type,organization,comment,address,subdistrict,district,province,status,timestamp_date,timestamp_month,timestamp_year,last_activity_date,last_activity_month,last_activity_year,longitude,latitude
18888,2022-66FWRF,"{คลอง,น้ำท่วม}","เขตห้วยขวาง,สำนักการระบายน้ำ กทม.,สำนักงานระบบ...",ผอ.สำนักระบายน้ำ \nขอน้ำเหนือดีๆจากรังสิตมาไล่...,503/1 พระราม 9 แขวง บางกะปิ เขตห้วยขวาง กรุงเท...,บางกะปิ,ห้วยขวาง,กรุงเทพมหานคร,done,19,10,2022,2,11,2022,100.58843,13.76295
28669,2022-79MCVE,{},"เขตป้อมปราบศัตรูพ่าย,สำนักการโยธา กทม.,สำนักงา...",พบหลุมขนาดใหญ่และลึกประมาณ1เมตรบริเวณห้าแยกพลั...,10110 แยกพลับพลาไชย 562 ถ. หลวง แขวง ป้อมปราบ ...,วัดเทพศิรินทร์,ป้อมปราบศัตรูพ่าย,กรุงเทพมหานคร,done,26,9,2022,21,2,2023,100.51172,13.74643
41262,2022-8NXRB4,{สายไฟ},"เขตบางนา,กรมทางหลวง,การไฟฟ้านครหลวง เขตบางนา,ก...",ฟุตบาทเป็นหลุมบ่อ มีน้ำขังเกือบตลอดเวลาช่วงฝนต...,194 ซอยบางนา-ตราด 27 ถนนบางนา-ตราด แขวงบางนา เ...,บางนาเหนือ,นา,กรุงเทพมหานคร,done,8,10,2022,10,10,2022,100.63947,13.66722

,ticket_id,type,organization,comment,address,subdistrict,district,province,status,timestamp_date,timestamp_month,timestamp_year,last_activity_date,last_activity_month,last_activity_year,longitude,latitude
8302,2022-3Y6DZL,"{กีดขวาง,ถนน,ทางเท้า}",กลุ่มงานโครงการก่อสร้างและบูรณะ ฝ่ายโยธา@ห้วยข...,ที่ถนนแยกเพชรบุรี-อโศก หน้าทางขึ้นลง MRT เพชรบ...,เพชรบุรี 7600 ถนน เพชรบุรี แขวง บางกะปิ เขตห้ว...,บางกะปิ,ห้วยขวาง,กรุงเทพมหานคร,done,21,6,2022,3,10,2022,100.56336,13.74843
10350,2022-47PHKF,{ถนน},"เขตบางรัก,สำนักการจราจรและขนส่ง กรุงเทพมหานคร ...",บริเวณทางม้าลายข้ามยากมาก เพราะทางม้าลายมาจบตร...,1096 ถ. เจริญกรุง แขวง บางรัก เขตบางรัก กรุงเท...,สี่พระยา,บางรัก,กรุงเทพมหานคร,done,8,6,2022,7,2,2023,100.51578,13.72913
18226,2022-63CFHG,{กีดขวาง},"เขตดินแดง,ฝ่ายเทศกิจ เขตดินแดง,ผอ.เขตดินแดง (น...",สรุปทางกทม. มีนโยบายให้จอดรถและขับขี่บนฟุตบาทห...,445 ซอย ประชาสงเคราะห์ 12 แขวง ดินแดง เขตดินแด...,ดินแดง,ดินแดง,กรุงเทพมหานคร,done,25,9,2022,3,11,2022,100.55954,13.77009

In [12]:
# Get the raw data of the differing rows for further investigation

df_raw_pandas_not_spark = raw_df[
    raw_df["ticket_id"].isin(df_pandas_not_spark["ticket_id"])
]
df_raw_spark_not_pandas = raw_df[
    raw_df["ticket_id"].isin(df_spark_not_pandas["ticket_id"])
]

In [13]:
if df_raw_pandas_not_spark.shape[0] > 0:
    display(df_raw_pandas_not_spark.head(3))

if df_raw_spark_not_pandas.shape[0] > 0:
    display(df_raw_spark_not_pandas.head(3))

,ticket_id,type,organization,comment,photo,photo_after,coords,address,subdistrict,district,province,timestamp,state,star,count_reopen,last_activity
21448,2022-66FWRF,"{คลอง,น้ำท่วม}","เขตห้วยขวาง,สำนักการระบายน้ำ กทม.,สำนักงานระบบ...",ผอ.สำนักระบายน้ำ \nขอน้ำเหนือดีๆจากรังสิตมาไล่...,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.58843,13.76295",503/1 พระราม 9 แขวง บางกะปิ เขตห้วยขวาง กรุงเท...,บางกะปิ,ห้วยขวาง,กรุงเทพมหานคร,2022-10-19 03:03:48.539656+00,เสร็จสิ้น,1.0,0,2022-11-02 01:50:44.088297+00
32624,2022-79MCVE,{},"เขตป้อมปราบศัตรูพ่าย,สำนักการโยธา กทม.,สำนักงา...",พบหลุมขนาดใหญ่และลึกประมาณ1เมตรบริเวณห้าแยกพลั...,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.51172,13.74643",10110 แยกพลับพลาไชย 562 ถ. หลวง แขวง ป้อมปราบ ...,วัดเทพศิรินทร์,ป้อมปราบศัตรูพ่าย,กรุงเทพมหานคร,2022-09-26 11:29:26.721514+00,เสร็จสิ้น,5.0,0,2023-02-21 06:54:13.220635+00
46917,2022-8NXRB4,{สายไฟ},"เขตบางนา,กรมทางหลวง,การไฟฟ้านครหลวง เขตบางนา,ก...",ฟุตบาทเป็นหลุมบ่อ มีน้ำขังเกือบตลอดเวลาช่วงฝนต...,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.63947,13.66722",194 ซอยบางนา-ตราด 27 ถนนบางนา-ตราด แขวงบางนา เ...,บางนาเหนือ,บางนา,กรุงเทพมหานคร,2022-10-08 14:11:29.537614+00,เสร็จสิ้น,NaN,0,2022-10-10 02:36:43.402716+00

,ticket_id,type,organization,comment,photo,photo_after,coords,address,subdistrict,district,province,timestamp,state,star,count_reopen,last_activity
9390,2022-3Y6DZL,"{กีดขวาง,ถนน,ทางเท้า}",กลุ่มงานโครงการก่อสร้างและบูรณะ ฝ่ายโยธา@ห้วยข...,ที่ถนนแยกเพชรบุรี-อโศก หน้าทางขึ้นลง MRT เพชรบ...,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.56336,13.74843",เพชรบุรี 7600 ถนน เพชรบุรี แขวง บางกะปิ เขตห้ว...,บางกะปิ,ห้วยขวาง,กรุงเทพมหานคร,2022-06-21 02:16:05.717115+00,เสร็จสิ้น,NaN,0,2022-10-03 13:46:49.564953+00
11722,2022-47PHKF,{ถนน},"เขตบางรัก,สำนักการจราจรและขนส่ง กรุงเทพมหานคร ...",บริเวณทางม้าลายข้ามยากมาก เพราะทางม้าลายมาจบตร...,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.51578,13.72913",1096 ถ. เจริญกรุง แขวง บางรัก เขตบางรัก กรุงเท...,สี่พระยา,บางรัก,กรุงเทพมหานคร,2022-06-08 03:49:55.263839+00,เสร็จสิ้น,1.0,0,2023-02-07 03:23:58.243656+00
20687,2022-63CFHG,{กีดขวาง},"เขตดินแดง,ฝ่ายเทศกิจ เขตดินแดง,ผอ.เขตดินแดง (น...",สรุปทางกทม. มีนโยบายให้จอดรถและขับขี่บนฟุตบาทห...,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.55954,13.77009",445 ซอย ประชาสงเคราะห์ 12 แขวง ดินแดง เขตดินแด...,ดินแดง,ดินแดง,กรุงเทพมหานคร,2022-09-25 07:32:13.297236+00,เสร็จสิ้น,NaN,3,2022-11-03 02:24:54.546557+00

---