# Data Scrapping

## Import necessary libraries

In [1]:
%pip install -qq -r ../requirements.txt

Note: you may need to restart the kernel to use updated packages.

In [2]:
# Add current directory to Python path for imports
import os
import sys

# Add the parent directory (project root) to Python path so we can import from src
project_root = os.path.dirname(os.getcwd())
if project_root not in sys.path:
    sys.path.append(project_root)

---

## Scrapping Population Data

### Year 2024 (2567 BE) - Bangkok Only

In [3]:
from src.scrapping import PopulationScrapping

# Scrape population for year: 2567 (2024), level: 'district'
scraper = PopulationScrapping(year=2567, level="district")
population_df = scraper.fetch_and_clean(save_to_csv=True)
population_df.head(5)

   province-name district-name   total  household
0  กรุงเทพมหานคร        พระนคร   39345      19016
1  กรุงเทพมหานคร         ดุสิต   74584      32869
2  กรุงเทพมหานคร       หนองจอก  186227      74844
3  กรุงเทพมหานคร        บางรัก   41701      36025
4  กรุงเทพมหานคร        บางเขน  184231     119489

In [4]:
# Scrape population for year: 2567 (2024), level: 'subdistrict'
scraper = PopulationScrapping(year=2567, level="subdistrict")
population_df = scraper.fetch_and_clean(save_to_csv=True)
population_df.head(5)

   province-name district-name subdistrict-name  total  household
0  กรุงเทพมหานคร        พระนคร  พระบรมมหาราชวัง   2884       1195
1  กรุงเทพมหานคร        พระนคร   วังบูรพาภิรมย์   8360       5322
2  กรุงเทพมหานคร        พระนคร       วัดราชบพิธ   2781        979
3  กรุงเทพมหานคร        พระนคร      สำราญราษฎร์   2619       1096
4  กรุงเทพมหานคร        พระนคร   ศาลเจ้าพ่อเสือ   2574       1001

---

### Year 2023 (2566 BE) - Bangkok Only

In [5]:
# Scrape population for year: 2566 (2023), level: 'district'
scraper = PopulationScrapping(year=2566, level="district")
population_df = scraper.fetch_and_clean(save_to_csv=True)
population_df.head(5)

   province-name district-name   total  household
0  กรุงเทพมหานคร        พระนคร   40254      19042
1  กรุงเทพมหานคร         ดุสิต   75814      32601
2  กรุงเทพมหานคร       หนองจอก  184138      73048
3  กรุงเทพมหานคร        บางรัก   42921      35410
4  กรุงเทพมหานคร        บางเขน  184611     117364

In [6]:
# Scrape population for year: 2566 (2023), level: 'subdistrict'
scraper = PopulationScrapping(year=2566, level="subdistrict")
population_df = scraper.fetch_and_clean(save_to_csv=True)
population_df.head(5)

   province-name district-name subdistrict-name  total  household
0  กรุงเทพมหานคร        พระนคร  พระบรมมหาราชวัง   2896       1195
1  กรุงเทพมหานคร        พระนคร   วังบูรพาภิรมย์   8489       5326
2  กรุงเทพมหานคร        พระนคร       วัดราชบพิธ   2846        979
3  กรุงเทพมหานคร        พระนคร      สำราญราษฎร์   2654       1105
4  กรุงเทพมหานคร        พระนคร   ศาลเจ้าพ่อเสือ   2676       1000

---

### Year 2022 (2565 BE) - Bangkok Only

In [7]:
# Scrape population for year: 2565 (2022), level: 'district'
scraper = PopulationScrapping(year=2565, level="district")
population_df = scraper.fetch_and_clean(save_to_csv=True)
population_df.head(5)

   province-name district-name   total  household
0  กรุงเทพมหานคร        พระนคร   41646      19100
1  กรุงเทพมหานคร         ดุสิต   78602      32404
2  กรุงเทพมหานคร       หนองจอก  181367      71054
3  กรุงเทพมหานคร        บางรัก   43914      35399
4  กรุงเทพมหานคร        บางเขน  185369     116209

In [8]:
# Scrape population for year: 2565 (2022), level: 'subdistrict'
scraper = PopulationScrapping(year=2565, level="subdistrict")
population_df = scraper.fetch_and_clean(save_to_csv=True)
population_df.head(5)

   province-name district-name subdistrict-name  total  household
0  กรุงเทพมหานคร        พระนคร  พระบรมมหาราชวัง   3137       1195
1  กรุงเทพมหานคร        พระนคร   วังบูรพาภิรมย์   8792       5361
2  กรุงเทพมหานคร        พระนคร       วัดราชบพิธ   2913        979
3  กรุงเทพมหานคร        พระนคร      สำราญราษฎร์   2712       1129
4  กรุงเทพมหานคร        พระนคร   ศาลเจ้าพ่อเสือ   2747       1000

---

### Year 2021 (2564 BE) - Bangkok Only

In [9]:
# Scrape population for year: 2564 (2021), level: 'district'
scraper = PopulationScrapping(year=2564, level="district")
population_df = scraper.fetch_and_clean(save_to_csv=True)
population_df.head(5)

   province-name district-name   total  household
0  กรุงเทพมหานคร        พระนคร   43062      19140
1  กรุงเทพมหานคร         ดุสิต   81494      31693
2  กรุงเทพมหานคร       หนองจอก  178856      68505
3  กรุงเทพมหานคร        บางรัก   45015      32664
4  กรุงเทพมหานคร        บางเขน  186200     115522

In [10]:
# Scrape population for year: 2564 (2021), level: 'subdistrict'
scraper = PopulationScrapping(year=2564, level="subdistrict")
population_df = scraper.fetch_and_clean(save_to_csv=True)
population_df.head(5)

   province-name district-name subdistrict-name  total  household
0  กรุงเทพมหานคร        พระนคร  พระบรมมหาราชวัง   3230       1207
1  กรุงเทพมหานคร        พระนคร   วังบูรพาภิรมย์   9124       5362
2  กรุงเทพมหานคร        พระนคร       วัดราชบพิธ   2964        979
3  กรุงเทพมหานคร        พระนคร      สำราญราษฎร์   2829       1128
4  กรุงเทพมหานคร        พระนคร   ศาลเจ้าพ่อเสือ   2859        999

---

## Scrapping Bangkok Index Data

In [11]:
from src.scrapping import BangkokIndexScrapping

scraper = BangkokIndexScrapping()
df_bangkok_index = scraper.fetch_and_clean(save_to_csv=True)
df_bangkok_index.head(5)

,district,total_score,public_service,economy,welfare,environment
0,ป้อมปราบศัตรูพ่าย,34.85,29.79,39.56,43.54,26.50
1,ปทุมวัน,34.75,38.79,48.69,35.13,16.38
2,พระนคร,34.75,28.88,41.56,38.08,30.50
3,สัมพันธวงศ์,33.53,26.21,43.19,41.08,23.63
4,ราชเทวี,32.32,37.92,38.31,26.67,26.38

In [12]:
df_bangkok_index.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   district        50 non-null     object
 1   total_score     50 non-null     float64
 2   public_service  50 non-null     float64
 3   economy         50 non-null     float64
 4   welfare         50 non-null     float64
 5   environment     50 non-null     float64
dtypes: float64(5), object(1)
memory usage: 2.5+ KB

---